### ISSUE TITLE
Замечания по Lab2

### ISSUE THREAD

**Issue by oMystique** [7kia/AndroidDevelopment#1]
- [ ] Переменная нигде не используется
```Java
    private String mPathToSaveFeed;
```

- [ ] *SCRO**LL**
```Java
    private static int SCROOL_SPEED = 10;
```

**Comment by oMystique** [comment]
- Многовато строк кода в функции. Следует зарефакторить
```Java
 private List<RssModel> getNextNewsFromRssFeed() throws XmlPullParserException, IOException {

        if ( mXmlPullParser == null) {
            mXmlPullParser = Xml.newPullParser();
            mXmlPullParser.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, false);
            mXmlPullParser.setInput( mInputStream, null);
        }

        mXmlPullParser.nextTag();

        List<RssModel> items = new ArrayList<>();
        String title = null;
        String link = null;
        String pubDate = null;
        boolean isItem = false;
        int currentNewId = 0;

        while (currentNewId < SCROOL_SPEED) {
            if ( mXmlPullParser.next() == XmlPullParser.END_DOCUMENT) {
                mInputStream.close();
                return items;
            }

            String name = mXmlPullParser.getName();
            if (name == null)
            {
                continue;
            }

            int eventType = mXmlPullParser.getEventType();
            if (eventType == XmlPullParser.END_TAG) {
                if (name.equalsIgnoreCase("item")) {
                    isItem = false;
                }
                continue;
            }
            if ((eventType == XmlPullParser.START_TAG)
                    && name.equalsIgnoreCase("item")) {
                isItem = true;
                continue;
            }

            String result = "";
            if ( mXmlPullParser.next() == XmlPullParser.TEXT) {
                result = mXmlPullParser.getText();
                mXmlPullParser.nextTag();
            }

            if (name.equalsIgnoreCase("title")) {
                title = result;
            } else if (name.equalsIgnoreCase("link")) {
                link = result;
            } else if (name.equalsIgnoreCase("pubDate")) {
                pubDate = result;
            }

            if ((title != null)
                    && (link != null)
                    && (pubDate != null)
                    ) {
                if (isItem) {
                    RssModel item = new RssModel(title, link, pubDate);
                    items.add(item);
                    currentNewId++;
                }

                title = null;
                link = null;
                pubDate = null;
                isItem = false;
            }
        }
        return items;
    }
```

**Comment by oMystique** [comment]
**RssService**

- [ ] Неиспользуемые данные
```Java
    private Handler mHandler;
    private Intent mMainIntent;
    private RssService self = this;
    private RssManager mRssManager;
```

**Comment by oMystique** [comment]
- [ ] Приложение падает при прокрутке списка контента
![default](https://user-images.githubusercontent.com/14878773/31055105-9ab387f0-a6c7-11e7-867e-a2507dc1e15d.png)
```Java
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.lab2, PID: 3439
                  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{7884a97 position=9 id=-1, oldPos=-1, pLpos:-1 no parent}
                      at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                      at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                      at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                      at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                      at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                      at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by oMystique** [comment]
- [ ] При запуске приложения, контент следует начинать подгружать сразу же, по факту старта активити, а не после того, как пользователь додумается использовать "Pull To Refresh"

**Comment by oMystique** [comment]
- [ ] Лучше так же использовать `strings`
```Java
    public String mPathToUrl = "https://lenta.ru/rss/news";
    public String mPathToSaveFeed = "feed";
    ==================================
    .setContentTitle("Lenta.ru RSS changed")
    .setContentText("There are new posts!")
    ==================================
    "Trying to refresh RSS feed",
```

**Comment by oMystique** [comment]
- [ ] Никем не используемый метод
```Java
    public void restartScrollListener(){
        mPreviousTotal = 0;
        mLoading = true;
        mFirstVisibleItem = 0;
        mVisibleItemCount = 0;
        mTotalItemCount = 0;
    }
```

**Comment by 7kia** [comment]
Исправлено.
https://github.com/7kia/AndroidDevelopment/commit/18e0805d2b3eaaad8f8d584f7d4cdb6119d9f760

**Comment by oMystique** [comment]
- [ ] `'catch' branch identical to 'IOException' branch`
```Java
            } catch (IOException e) {
                e.printStackTrace();
            } catch (XmlPullParserException e) {
                e.printStackTrace();
            }
```

**Comment by 7kia** [comment]
Исправил
https://github.com/7kia/AndroidDevelopment/commit/1e42b07744e1c8a57084863958b528d934974884
